name: Daily Update Workflow

on:
  schedule:
    - cron: '21 7 * * *'

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Append Random Emoji to File
        run: |
          EMOJI_LIST=("ðŸ˜€" "ðŸ˜ƒ" "ðŸ˜„" "ðŸ˜" "ðŸ˜†" "ðŸ˜…" "ðŸ˜‚" "ðŸ¤£" "ðŸ˜Š" "ðŸ˜‡" "ðŸ™‚" "ðŸ™ƒ" "ðŸ˜‰" "ðŸ˜Œ" "ðŸ˜" "ðŸ¥°" "ðŸ˜˜" "ðŸ˜—" "ðŸ˜™" "ðŸ˜š" "ðŸ˜‹" "ðŸ˜›" "ðŸ˜œ" "ðŸ˜" "ðŸ¤ª" "ðŸ¤¨" "ðŸ§" "ðŸ¤“" "ðŸ˜Ž" "ðŸ¥³")
          RANDOM_EMOJI=${EMOJI_LIST[$RANDOM % ${#EMOJI_LIST[@]}]}
          echo "$RANDOM_EMOJI" >> test.md

      - name: Commit Changes to Repository
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "pashelnaher"
          author_email: "dixibn4kn@gmail.com"
          message: "Daily contribution update"
          add: "test.md"

      - name: Push Changes to Branch
        uses: ad-m/github-push-action@master
        with:
          branch: daily-contribution
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Automated Daily Contribution"
          commit-message: "Automated daily update with random emoji"
          branch: daily-contribution
          base: main
          body: "This pull request was automatically generated as part of the daily update workflow."
          token: ${{ secrets.GITHUB_TOKEN }}
